// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// @ts-nocheck
import "dotenv/config";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
